version: '3.9'

services:
  postgres:
    image: postgres:latest
    env_file:
      - ./db.env
    volumes:
      - ./db_dump/db-dump.sql:/docker-entrypoint-initdb.d/init-user-db.sh
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  back:
    build: .
    container_name: wb-test
    restart: on-failure
    env_file:
      - ./config.env
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  db-data:
    driver: local